import { useEffect, useRef, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Download, RotateCcw, TrendingUp, Upload } from 'lucide-react';
import historical from './data/historical.json';
import { forecast, type Assumptions, type ChannelAssumption } from './engine/forecast';
import './styles.css';

const pct = (n:number) => `${(n*100).toFixed(1)}%`;
const money = (n:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:0,maximumFractionDigits:1}).format(n);
const number = (n:number) => new Intl.NumberFormat('en-US',{minimumFractionDigits:0,maximumFractionDigits:1}).format(n);
const whole = (n:number) => new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
const one = (n:number) => Number(n.toFixed(1));
const defaults: Assumptions = { months:12, monthlyTrafficGrowth:.03, signupRate:.137, purchaseRate:.008, voluntaryCustomerChurn:.045, delinquentCustomerChurn:.012, voluntaryRevenueChurn:.045, delinquentRevenueChurn:.012, expansionRate:.018, retractionRate:.006, newCustomerArpu:38, grossMargin:.85, targetLtvCac:3, monthlyIncrementalVisitors:0 };
const scenarios: Record<string,Partial<Assumptions>> = { Conservative:{monthlyTrafficGrowth:0,signupRate:.11,purchaseRate:.005}, Baseline:{monthlyTrafficGrowth:.03,signupRate:.137,purchaseRate:.008}, Ambitious:{monthlyTrafficGrowth:.08,signupRate:.17,purchaseRate:.012} };
type ChannelModel='manual'|'cpc'|'cpm';
type EditableChannel=ChannelAssumption & {model:ChannelModel;allocation:number;cpc:number;cpm:number;ctr:number;hidden:boolean};
const makeChannel=(name:string,model:ChannelModel,allocation=0):EditableChannel=>({name,model,allocation,cpc:2,cpm:20,ctr:.008,visitors:0,goLiveMonth:1,signupRate:.137,purchaseRate:.008,arpu:38,hidden:false});
const initialChannels=()=>[
 makeChannel('SEO / organic','manual'),makeChannel('Partners','manual'),
 makeChannel('Meta','cpc',.25),makeChannel('Reddit','cpc',.10),makeChannel('Pinterest','cpc',.10),makeChannel('LinkedIn','cpc',.10),makeChannel('TikTok','cpc',.10),makeChannel('Snapchat','cpc',.05),
 makeChannel('YouTube','cpm',.15),makeChannel('Display','cpm',.10),makeChannel('CTV (Vibe.co / Quantcast)','cpm',.05),
 makeChannel('Enterprise / B2B','manual'),makeChannel('Custom','manual')
];

type NumericKey = keyof Assumptions;
const fields: {key:NumericKey; label:string; step:number; kind:'pct'|'number'|'money'; hint:string}[] = [
 {key:'months',label:'Forecast range',step:1,kind:'number',hint:'Months ahead'}, {key:'monthlyTrafficGrowth',label:'Traffic growth',step:.005,kind:'pct',hint:'Monthly'},
 {key:'signupRate',label:'Visitor → signup',step:.005,kind:'pct',hint:'Mixpanel baseline'}, {key:'purchaseRate',label:'Signup → purchase',step:.01,kind:'pct',hint:'Paid conversion'},
 {key:'voluntaryCustomerChurn',label:'Voluntary logo churn',step:.005,kind:'pct',hint:'Monthly'}, {key:'delinquentCustomerChurn',label:'Delinquent logo churn',step:.0025,kind:'pct',hint:'Monthly'},
 {key:'voluntaryRevenueChurn',label:'Voluntary revenue churn',step:.005,kind:'pct',hint:'Monthly'}, {key:'delinquentRevenueChurn',label:'Delinquent revenue churn',step:.0025,kind:'pct',hint:'Monthly'},
 {key:'expansionRate',label:'Expansion rate',step:.0025,kind:'pct',hint:'Existing MRR'}, {key:'retractionRate',label:'Downgrade rate',step:.0025,kind:'pct',hint:'Existing MRR'},
 {key:'newCustomerArpu',label:'New customer ARPU',step:1,kind:'money',hint:'Monthly'}, {key:'grossMargin',label:'Gross margin',step:.01,kind:'pct',hint:'Contribution LTV'},
 {key:'targetLtvCac',label:'Target LTV:CAC',step:.25,kind:'number',hint:'Efficiency target'}
];
function Field({f,a,setA}:{f:typeof fields[number];a:Assumptions;setA:(a:Assumptions)=>void}) { const display=one(f.kind==='pct'?a[f.key]*100:a[f.key]); return <label className="field"><span>{f.label}<small>{f.hint}</small></span><div className="input"><input aria-label={f.label} type="number" min="0" step={f.kind==='pct'?f.step*100:f.step} value={display} onChange={e=>setA({...a,[f.key]:f.kind==='pct'?+e.target.value/100:+e.target.value})}/><b>{f.kind==='pct'?'%':f.kind==='money'?'$':''}</b></div></label> }
function ChannelRow({channel:c,modeled,index,budget,setChannels,channels}:{channel:EditableChannel;modeled:EditableChannel;index:number;budget:number;setChannels:(c:EditableChannel[])=>void;channels:EditableChannel[]}){
 const update=(patch:Partial<EditableChannel>)=>setChannels(channels.map((x,i)=>i===index?{...x,...patch}:x)); const spend=c.goLiveMonth===0?0:budget*c.allocation; const impliedCpc=modeled.visitors?spend/modeled.visitors:0;
 return <details className="channel"><summary><strong>{c.name}</strong><label>Live month<input aria-label={`${c.name} goLiveMonth`} type="number" min="0" max="60" step="1" value={c.goLiveMonth} onChange={e=>update({goLiveMonth:+e.target.value})}/></label>{c.model==='manual'?<label>Launch visitors<input aria-label={`${c.name} visitors`} type="number" min="0" step="100" value={one(c.visitors)} onChange={e=>update({visitors:+e.target.value})}/></label>:<><label>Budget %<input aria-label={`${c.name} allocation`} type="number" min="0" max="100" step="1" value={one(c.allocation*100)} onChange={e=>update({allocation:+e.target.value/100})}/><small>{money(spend)}</small></label>{c.model==='cpc'?<label>CPC<input aria-label={`${c.name} cpc`} type="number" min="0" step=".1" value={one(c.cpc)} onChange={e=>update({cpc:+e.target.value})}/></label>:<><label>CPM<input aria-label={`${c.name} cpm`} type="number" min="0" step=".1" value={one(c.cpm)} onChange={e=>update({cpm:+e.target.value})}/></label><label>CTR %<input aria-label={`${c.name} ctr`} type="number" min="0" step=".1" value={one(c.ctr*100)} onChange={e=>update({ctr:+e.target.value/100})}/></label></>}</>}<span className="traffic"><b>{number(modeled.visitors)}</b> visits<small>{c.model!=='manual'?`${money(impliedCpc)} expected CPC`:''}</small></span></summary><div className="channelAdvanced"><label>Visitor → signup %<input aria-label={`${c.name} signupRate`} type="number" min="0" step=".1" value={one(c.signupRate*100)} onChange={e=>update({signupRate:+e.target.value/100})}/></label><label>Signup → purchase %<input aria-label={`${c.name} purchaseRate`} type="number" min="0" step=".1" value={one(c.purchaseRate*100)} onChange={e=>update({purchaseRate:+e.target.value/100})}/></label><label>New customer ARPU<input aria-label={`${c.name} arpu`} type="number" min="0" step=".1" value={one(c.arpu)} onChange={e=>update({arpu:+e.target.value})}/></label><button className="hideChannel" onClick={()=>update({hidden:!c.hidden})}>{c.hidden?'Restore subchannel':'Hide subchannel'}</button></div></details>
}

export default function App(){
 const fileInput=useRef<HTMLInputElement>(null); const [importMessage,setImportMessage]=useState(''); const [modelName,setModelName]=useState('Growth Model'); const [pageView,setPageView]=useState<'forecast'|'channels'|'methodology'>('forecast'); const [channelTab,setChannelTab]=useState<ChannelModel>('cpc'); const [showHidden,setShowHidden]=useState(false);
 const [a,setA]=useState(defaults); const [scenario,setScenario]=useState('Baseline'); const [budget,setBudget]=useState(50000); const [channels,setChannels]=useState(initialChannels); const complete=historical.months.filter(m=>!m.partial); const last=complete.at(-1)!;
 useEffect(()=>{document.title=`${modelName || 'Growth Model'} Forecast`},[modelName]);
 const modeledChannels=channels.map(c=>{const spend=c.goLiveMonth===0?0:budget*c.allocation;const visitors=c.goLiveMonth===0?0:c.model==='cpc'?(c.cpc?spend/c.cpc:0):c.model==='cpm'?(c.cpm?spend/c.cpm*1000*c.ctr:0):c.visitors;return {...c,visitors}});
 const channelVisitors=modeledChannels.reduce((sum,c)=>sum+c.visitors,0); const allocation=channels.reduce((sum,c)=>sum+(c.goLiveMonth===0?0:c.allocation),0);
 const projection=forecast({month:last.month,visitors:last.visitors!,customers:last.customers,mrr:last.mrr},a,modeledChannels); const end=projection.at(-1)!;
 const paidLaunch=modeledChannels.filter(c=>c.model!=='manual'&&c.goLiveMonth>0).reduce((t,c)=>{const customers=c.visitors*c.signupRate*c.purchaseRate;return {spend:t.spend+budget*c.allocation,customers:t.customers+customers}}, {spend:0,customers:0});
 const blendedCac=paidLaunch.customers?paidLaunch.spend/paidLaunch.customers:0; const predictedLtv=end.ltv*a.grossMargin; const payback=end.arpu*a.grossMargin?blendedCac/(end.arpu*a.grossMargin):0; const expectedLtvCac=blendedCac?predictedLtv/blendedCac:0;
 const trend=[...complete.slice(-12).map(m=>({month:m.month,mrr:m.mrr,customers:m.customers,type:'Actual'})),...projection.map(m=>({month:m.month,mrr:m.endingMrr,customers:m.customers,type:'Forecast'}))];
 const bridge=projection.map(m=>({month:m.month,New:m.newMrr,Expansion:m.expansionMrr,Downgrade:-m.retractionMrr,Churn:-m.churnMrr}));
 const download=(name:string,body:string,type:string)=>{const u=URL.createObjectURL(new Blob([body],{type}));const x=document.createElement('a');x.href=u;x.download=name;x.click();URL.revokeObjectURL(u)};
 const exportCsv=()=>{const keys=Object.keys(projection[0]) as (keyof typeof end)[];download(`${(modelName||'growth-model').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-forecast.csv`,[keys.join(','),...projection.map(r=>keys.map(k=>r[k]).join(','))].join('\n'),'text/csv')};
 const exportAssumptions=()=>download(`${(modelName||'growth-model').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}-assumptions.json`,JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),modelName,scenario,budget,assumptions:a,channels},null,2),'application/json');
 const importAssumptions=async(file?:File)=>{if(!file)return;try{const value=JSON.parse(await file.text()) as {schemaVersion?:number;modelName?:string;scenario?:string;budget?:number;assumptions?:Assumptions;channels?:EditableChannel[]};if(value.schemaVersion!==1||!value.assumptions||!Array.isArray(value.channels)||typeof value.budget!=='number')throw new Error('Unsupported or incomplete assumption file');const nums=[...Object.values(value.assumptions),value.budget,...value.channels.flatMap(c=>[c.visitors,c.goLiveMonth,c.signupRate,c.purchaseRate,c.arpu,c.allocation,c.cpc,c.cpm,c.ctr])];if(nums.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0)||value.channels.some(c=>!['manual','cpc','cpm'].includes(c.model)))throw new Error('Assumption file contains invalid values');setA(value.assumptions);setBudget(value.budget);setChannels(value.channels);setModelName(typeof value.modelName==='string'&&value.modelName.trim()?value.modelName.trim():'Growth Model');setScenario(value.scenario||'Imported');setImportMessage(`Loaded ${file.name}`)}catch(error){setImportMessage(error instanceof Error?error.message:'Could not load assumption file')}finally{if(fileInput.current)fileInput.current.value=''}};
 return <main><header><div><label className="modelName"><span>Model name</span><input aria-label="Model name" value={modelName} placeholder="Enter a name" onChange={e=>setModelName(e.target.value)}/></label><h1>{pageView==='forecast'?'Growth forecast':pageView==='channels'?'Channel settings':'Methodology'}</h1><nav className="pageNav"><button className={pageView==='forecast'?'active':''} onClick={()=>setPageView('forecast')}>Forecast</button><button className={pageView==='channels'?'active':''} onClick={()=>setPageView('channels')}>Channels</button><button className={pageView==='methodology'?'active':''} onClick={()=>setPageView('methodology')}>Methodology</button></nav><p>{pageView==='forecast'?'Change a lever. See the revenue consequence.':pageView==='channels'?'Configure acquisition channels without crowding the forecast.':'How assumptions flow through the monthly model.'}</p></div><div className="headerActions"><button onClick={()=>{setA(defaults);setChannels(initialChannels());setBudget(50000);setModelName('Growth Model');setScenario('Baseline');setImportMessage('')}}><RotateCcw size={16}/> Reset</button><button onClick={()=>fileInput.current?.click()}><Upload size={16}/> Load assumptions</button><input ref={fileInput} className="fileInput" aria-label="Assumptions JSON file" type="file" accept="application/json,.json" onChange={e=>importAssumptions(e.target.files?.[0])}/><button onClick={exportAssumptions}><Download size={16}/> Export assumptions</button><button className="primary" onClick={exportCsv}><Download size={16}/> Export forecast</button></div></header>{importMessage&&<div className="importMessage" role="status">{importMessage}</div>}
 <section className={`layout ${pageView==='channels'?'channelMode':pageView==='methodology'?'methodMode':'forecastMode'}`}><aside><div className="panelHead"><h2>Assumptions</h2><span>{scenario}</span></div><div className="scenarioTabs">{Object.keys(scenarios).map(name=><button className={scenario===name?'active':''} key={name} onClick={()=>{setScenario(name);setA({...a,...scenarios[name]})}}>{name}</button>)}</div>{fields.slice(0,4).map(f=><Field key={f.key} f={f} a={a} setA={v=>{setScenario('Custom');setA(v)}}/>)}<details className="advanced"><summary>Advanced assumptions</summary>{fields.slice(4).map(f=><Field key={f.key} f={f} a={a} setA={v=>{setScenario('Custom');setA(v)}}/>)}</details></aside><div className="dashboard">
 <section className="cards"><article><small>ENDING MRR</small><strong>{money(end.endingMrr)}</strong><em>{pct(end.endingMrr/last.mrr-1)} vs Jul 2026</em></article><article><small>ENDING ARR</small><strong>{money(end.arr)}</strong><em>{a.months}-month run rate</em></article><article><small>TOTAL CUSTOMERS</small><strong>{whole(end.customers)}</strong><em>+{whole(end.customers-last.customers)} net</em></article><article><small>MAX CAC</small><strong>{money(end.maxCac)}</strong><em>{a.targetLtvCac}:1 contribution LTV:CAC</em></article></section>
 <section className="cards secondaryCards"><article><small>PAYBACK PERIOD</small><strong>{number(payback)} mo</strong><em>Blended CAC ÷ monthly contribution ARPU</em></article><article><small>PREDICTED LTV</small><strong>{money(predictedLtv)}</strong><em>Contribution-margin adjusted</em></article><article><small>ACTUAL BLENDED CAC</small><strong>{money(blendedCac)}</strong><em>Paid launch spend ÷ paid new customers</em></article><article><small>EXPECTED LTV:CAC</small><strong>{number(expectedLtvCac)}:1</strong><em>Predicted LTV ÷ blended CAC</em></article></section>
 <section className="channelCard"><div className="chartTitle"><div><h2>Channel assumptions</h2><p>Each channel adds traffic once in its go-live month; all active traffic then compounds at the global Traffic growth rate</p></div><b>+{number(channelVisitors)} launch visitors</b></div><div className="budgetBar"><label>Paid media budget <span><b>$</b><input aria-label="Paid media budget" type="number" min="0" step="1000" value={budget} onChange={e=>setBudget(+e.target.value)}/><small>/ mo</small></span></label><label>Allocated <strong className={Math.abs(allocation-1)>.001?'warn':''}>{pct(allocation)} · {money(budget*allocation)}</strong></label></div><div className="channelTabs"><button className={channelTab==='cpc'?'active':''} onClick={()=>setChannelTab('cpc')}>Direct Response</button><button className={channelTab==='cpm'?'active':''} onClick={()=>setChannelTab('cpm')}>Demand Gen</button><button className={channelTab==='manual'?'active':''} onClick={()=>setChannelTab('manual')}>Owned / Partner / Custom</button><button className="showHidden" onClick={()=>setShowHidden(!showHidden)}>{showHidden?'Hide hidden':`Show hidden (${channels.filter(c=>c.hidden).length})`}</button></div><div className="channelGroups">{channels.map((c,i)=>({c,i})).filter(({c})=>c.model===channelTab&&(!c.hidden||showHidden)).map(({c,i})=><ChannelRow key={c.name} channel={c} modeled={modeledChannels[i]} index={i} budget={budget} setChannels={setChannels} channels={channels}/>)}</div></section>
 <section className="methodCard"><div className="methodIntro"><h2>How to use this model</h2><p>Start with the Baseline scenario, configure channel launches, then change one assumption at a time. The forecast runs month by month from July 2026, the last complete historical month.</p></div><div className="methodGrid"><article><span>01</span><h3>Baseline traffic</h3><p>Each month begins with the previous month’s baseline visitors multiplied by <b>1 + Traffic growth</b>.</p><code>next visitors = prior visitors × (1 + growth)</code></article><article><span>02</span><h3>Channel launches</h3><p>A channel adds traffic once in its Live month. Month 0 disables it. After launch, its traffic compounds at the global Traffic growth rate.</p><code>channel traffic = launch traffic × (1 + growth)</code></article><article><span>03</span><h3>Paid traffic</h3><p>Direct response uses allocated spend and CPC. Demand generation uses allocated spend, CPM, and CTR.</p><code>DR = spend ÷ CPC<br/>Demand = spend ÷ CPM × 1,000 × CTR</code></article><article><span>04</span><h3>Funnel</h3><p>Baseline traffic uses the main conversion assumptions. A channel uses its own expanded signup and purchase assumptions.</p><code>customers = visitors × signup % × purchase %</code></article><article><span>05</span><h3>Customer bridge</h3><p>New customers are added while voluntary and delinquent logo churn remove customers from the opening balance.</p><code>ending customers = opening + new − churned</code></article><article><span>06</span><h3>Revenue bridge</h3><p>New and expansion MRR are added; downgrade and revenue churn MRR are removed.</p><code>ending MRR = opening + new + expansion − downgrade − churn</code></article><article><span>07</span><h3>Unit economics</h3><p>Predicted LTV uses ending ARPU, gross margin, and revenue churn. Blended CAC uses paid launch spend and the new customers attributable to that launch traffic.</p><code>LTV = ARPU × margin ÷ revenue churn<br/>CAC = paid spend ÷ paid new customers</code></article><article><span>08</span><h3>Read the result</h3><p>Payback shows months needed to recover blended CAC from monthly contribution ARPU. Expected LTV:CAC compares predicted contribution LTV with blended CAC.</p><code>payback = CAC ÷ (ARPU × margin)<br/>LTV:CAC = predicted LTV ÷ CAC</code></article></div><div className="methodNotes"><h3>Recommended workflow</h3><ol><li>Name the model and export a clean Baseline assumption set.</li><li>Set each channel’s Live month; use 0 for channels outside the plan.</li><li>Make paid allocations total 100% and enter CPC or CPM/CTR expectations.</li><li>Expand channels only when their conversion or ARPU differs from Baseline.</li><li>Compare ending MRR, payback, blended CAC, and expected LTV:CAC.</li><li>Export the assumptions JSON and forecast CSV for review.</li></ol></div></section>
 <section className="chartCard wide"><div className="chartTitle"><div><h2>MRR trajectory</h2><p>Actual history and assumption-driven forecast</p></div><TrendingUp size={22}/></div><ResponsiveContainer width="100%" height={300}><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff6b4a" stopOpacity=".35"/><stop offset="1" stopColor="#ff6b4a" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickFormatter={v=>v.slice(2)} minTickGap={30}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>money(Number(v))}/><Area type="monotone" dataKey="mrr" stroke="#ff6b4a" fill="url(#fill)" strokeWidth={3}/></AreaChart></ResponsiveContainer></section>
 <div className="chartGrid"><section className="chartCard"><div className="chartTitle"><div><h2>Revenue bridge</h2><p>Monthly MRR movement</p></div></div><ResponsiveContainer width="100%" height={260}><BarChart data={bridge}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickFormatter={v=>v.slice(5)}/><YAxis tickFormatter={v=>`$${Math.round(v/1000)}k`}/><Tooltip formatter={(v)=>money(Number(v))}/><Legend/><Bar dataKey="New" stackId="a" fill="#ff6b4a"/><Bar dataKey="Expansion" stackId="a" fill="#7b61ff"/><Bar dataKey="Downgrade" stackId="a" fill="#f1b84b"/><Bar dataKey="Churn" stackId="a" fill="#27282a"/></BarChart></ResponsiveContainer></section><section className="chartCard"><div className="chartTitle"><div><h2>Customer growth</h2><p>Logos, signups, and new customers</p></div></div><ResponsiveContainer width="100%" height={260}><AreaChart data={projection}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickFormatter={v=>v.slice(5)}/><YAxis/><Tooltip/><Legend/><Line type="monotone" dataKey="customers" stroke="#27282a" strokeWidth={3}/><Line type="monotone" dataKey="signups" stroke="#7b61ff"/><Line type="monotone" dataKey="newCustomers" stroke="#ff6b4a"/></AreaChart></ResponsiveContainer></section></div>
 <section className="tableCard"><div className="chartTitle"><div><h2>Monthly forecast</h2><p>Every output traces to the assumptions at left</p></div></div><div className="tableWrap"><table><thead><tr><th>Month</th><th>Visitors</th><th>Signups</th><th>New customers</th><th>Total customers</th><th>ARPU</th><th>Ending MRR</th><th>Ending ARR</th><th>Max CAC</th><th>Max cost/signup</th></tr></thead><tbody>{projection.map(r=><tr key={r.month}><td>{r.month}</td><td>{whole(r.visitors)}</td><td>{whole(r.signups)}</td><td>{whole(r.newCustomers)}</td><td>{whole(r.customers)}</td><td>{money(r.arpu)}</td><td><b>{money(r.endingMrr)}</b></td><td><b>{money(r.arr)}</b></td><td>{money(r.maxCac)}</td><td>{money(r.maxCostPerSignup)}</td></tr>)}</tbody></table></div></section>
 </div></section><footer>Historical source: ChartMogul exports + Mixpanel project 2352617 · Complete data through July 2026</footer></main>
}
